name: transmission
description: Communicating with Transmission using RPC
version: 0.2.0
homepage: https://github.com/ethicnology/dart-transmission

environment:
  sdk: '>=2.17.0'

dependencies:
  dio: '>=5.3.0'
  

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  dotenv: ^4.1.0