name: transmission
description: Flutter package to talk to a Transmission torrent instance
version: 0.1.1
homepage: https://github.com/ethicnology/dart-transmission

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dio: '>=5.3.0'
  

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0